name: Test

on:
  workflow_dispatch:

jobs:
  trivy:  
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ghcr.io/radiorabe/ubi9-minimal:latest
          format: 'json'
          ignore-unfixed: true
          list-all-pkgs: true
          scanners: 'vuln'
          output: 'trivy.json'

      - name: Convert trivy results to sarif
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: trivy.json
          scan-type: 'convert'
          format: 'sarif'
          # we don't actual limit them, but this gates convert
          limit-severities-for-sarif: true
          # empty makes it skip the --vuln-type arg
          vuln-type: ''
          output: 'trivy.sarif'

      - run: cat trivy.sarif
